/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tea_1.glb --types 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GroupProps } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane002: THREE.Mesh;
    Sphere: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Cube001: THREE.Mesh;
    Torus: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Sphere011: THREE.Mesh;
    Sphere012: THREE.Mesh;
    Sphere013: THREE.Mesh;
    Sphere014: THREE.Mesh;
    Sphere015: THREE.Mesh;
    Sphere016: THREE.Mesh;
    Sphere017: THREE.Mesh;
    Sphere018: THREE.Mesh;
    Sphere019: THREE.Mesh;
    Sphere021: THREE.Mesh;
    Sphere025: THREE.Mesh;
    Sphere027: THREE.Mesh;
    Sphere028: THREE.Mesh;
    Sphere029: THREE.Mesh;
    Sphere030: THREE.Mesh;
    Sphere032: THREE.Mesh;
    Sphere033: THREE.Mesh;
    Sphere034: THREE.Mesh;
    Sphere035: THREE.Mesh;
    Sphere036: THREE.Mesh;
    Sphere037: THREE.Mesh;
    Sphere038: THREE.Mesh;
    Sphere039: THREE.Mesh;
    Sphere040: THREE.Mesh;
    Sphere041: THREE.Mesh;
    Sphere042: THREE.Mesh;
    Sphere043: THREE.Mesh;
    Sphere044: THREE.Mesh;
    Sphere045: THREE.Mesh;
    Sphere046: THREE.Mesh;
    Sphere049: THREE.Mesh;
    Sphere050: THREE.Mesh;
    Sphere051: THREE.Mesh;
    Sphere052: THREE.Mesh;
    Sphere053: THREE.Mesh;
    Sphere054: THREE.Mesh;
    Sphere056: THREE.Mesh;
    Sphere057: THREE.Mesh;
    Sphere058: THREE.Mesh;
    Sphere059: THREE.Mesh;
    Sphere060: THREE.Mesh;
    Sphere061: THREE.Mesh;
    Sphere062: THREE.Mesh;
    Sphere063: THREE.Mesh;
    Sphere064: THREE.Mesh;
    Sphere065: THREE.Mesh;
    Sphere066: THREE.Mesh;
    Sphere067: THREE.Mesh;
    Sphere068: THREE.Mesh;
    Sphere069: THREE.Mesh;
    Sphere070: THREE.Mesh;
    Sphere071: THREE.Mesh;
    Sphere072: THREE.Mesh;
    Sphere073: THREE.Mesh;
    Sphere074: THREE.Mesh;
    Sphere075: THREE.Mesh;
    Sphere076: THREE.Mesh;
    Sphere077: THREE.Mesh;
    Sphere078: THREE.Mesh;
    Sphere079: THREE.Mesh;
    Sphere080: THREE.Mesh;
    Sphere081: THREE.Mesh;
    Sphere082: THREE.Mesh;
    Sphere083: THREE.Mesh;
    Sphere084: THREE.Mesh;
    Sphere086: THREE.Mesh;
    Sphere087: THREE.Mesh;
    Sphere088: THREE.Mesh;
    Sphere089: THREE.Mesh;
    Sphere090: THREE.Mesh;
    Sphere091: THREE.Mesh;
    Sphere092: THREE.Mesh;
    Sphere093: THREE.Mesh;
    Sphere094: THREE.Mesh;
    Sphere095: THREE.Mesh;
    Sphere096: THREE.Mesh;
    Sphere097: THREE.Mesh;
    Sphere098: THREE.Mesh;
    Sphere099: THREE.Mesh;
    Sphere100: THREE.Mesh;
    Sphere101: THREE.Mesh;
    Sphere102: THREE.Mesh;
    Sphere103: THREE.Mesh;
    Sphere104: THREE.Mesh;
    Sphere105: THREE.Mesh;
    Sphere106: THREE.Mesh;
    Sphere107: THREE.Mesh;
    Sphere108: THREE.Mesh;
    Sphere109: THREE.Mesh;
    Sphere112: THREE.Mesh;
    Sphere114: THREE.Mesh;
    Sphere116: THREE.Mesh;
    Sphere117: THREE.Mesh;
    Sphere118: THREE.Mesh;
    Sphere119: THREE.Mesh;
    Sphere121: THREE.Mesh;
    Sphere122: THREE.Mesh;
    Sphere123: THREE.Mesh;
    Sphere125: THREE.Mesh;
    Sphere126: THREE.Mesh;
    Sphere127: THREE.Mesh;
    Sphere128: THREE.Mesh;
    Sphere129: THREE.Mesh;
    Sphere130: THREE.Mesh;
    Sphere131: THREE.Mesh;
    Sphere133: THREE.Mesh;
    Sphere134: THREE.Mesh;
    Sphere135: THREE.Mesh;
    Sphere138: THREE.Mesh;
    Sphere139: THREE.Mesh;
    Sphere140: THREE.Mesh;
    Sphere141: THREE.Mesh;
    Sphere142: THREE.Mesh;
    Sphere143: THREE.Mesh;
    Sphere144: THREE.Mesh;
    Sphere145: THREE.Mesh;
    Sphere146: THREE.Mesh;
    Sphere147: THREE.Mesh;
    Sphere148: THREE.Mesh;
    Sphere149: THREE.Mesh;
    Sphere150: THREE.Mesh;
    Sphere151: THREE.Mesh;
    Sphere152: THREE.Mesh;
    Sphere153: THREE.Mesh;
    Sphere154: THREE.Mesh;
    Sphere155: THREE.Mesh;
    Sphere156: THREE.Mesh;
    Sphere157: THREE.Mesh;
    Sphere158: THREE.Mesh;
    Sphere159: THREE.Mesh;
    Sphere160: THREE.Mesh;
    Sphere162: THREE.Mesh;
    Sphere163: THREE.Mesh;
    Sphere164: THREE.Mesh;
    Sphere165: THREE.Mesh;
    Sphere166: THREE.Mesh;
    Sphere167: THREE.Mesh;
    Sphere168: THREE.Mesh;
    Sphere169: THREE.Mesh;
    Sphere170: THREE.Mesh;
    Sphere172: THREE.Mesh;
    Sphere173: THREE.Mesh;
    Sphere174: THREE.Mesh;
    Sphere175: THREE.Mesh;
    Sphere176: THREE.Mesh;
    Sphere177: THREE.Mesh;
    Sphere178: THREE.Mesh;
    Sphere179: THREE.Mesh;
    Sphere180: THREE.Mesh;
    Sphere181: THREE.Mesh;
    Sphere182: THREE.Mesh;
    Sphere183: THREE.Mesh;
    Sphere184: THREE.Mesh;
    Sphere185: THREE.Mesh;
    Sphere187: THREE.Mesh;
    Sphere189: THREE.Mesh;
    Sphere191: THREE.Mesh;
    Sphere192: THREE.Mesh;
    Sphere194: THREE.Mesh;
    Sphere195: THREE.Mesh;
    Sphere197: THREE.Mesh;
    Sphere198: THREE.Mesh;
    Sphere199: THREE.Mesh;
    Sphere200: THREE.Mesh;
    Sphere201: THREE.Mesh;
    Sphere202: THREE.Mesh;
    Sphere203: THREE.Mesh;
    Sphere204: THREE.Mesh;
    Sphere205: THREE.Mesh;
    Sphere206: THREE.Mesh;
    Sphere207: THREE.Mesh;
    Sphere208: THREE.Mesh;
    Sphere209: THREE.Mesh;
    Sphere210: THREE.Mesh;
    Sphere211: THREE.Mesh;
    Sphere212: THREE.Mesh;
    Sphere213: THREE.Mesh;
    Sphere214: THREE.Mesh;
    Sphere215: THREE.Mesh;
    Sphere216: THREE.Mesh;
    Sphere217: THREE.Mesh;
    Sphere218: THREE.Mesh;
    Sphere219: THREE.Mesh;
    Sphere220: THREE.Mesh;
    Sphere221: THREE.Mesh;
    Sphere222: THREE.Mesh;
    Sphere223: THREE.Mesh;
    Sphere224: THREE.Mesh;
    Sphere225: THREE.Mesh;
    Sphere226: THREE.Mesh;
    Sphere227: THREE.Mesh;
    Sphere228: THREE.Mesh;
    Sphere229: THREE.Mesh;
    Sphere230: THREE.Mesh;
    Sphere231: THREE.Mesh;
    Sphere232: THREE.Mesh;
    Sphere233: THREE.Mesh;
    Sphere234: THREE.Mesh;
    Sphere235: THREE.Mesh;
    Sphere236: THREE.Mesh;
    Sphere237: THREE.Mesh;
    Sphere238: THREE.Mesh;
    Sphere239: THREE.Mesh;
    Sphere240: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    cup: THREE.MeshStandardMaterial;
    茶: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    Fur: THREE.MeshStandardMaterial;
    Furskin: THREE.MeshStandardMaterial;
    eye: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

interface ModelProps extends GroupProps {
  colors?: string[]; // colorsプロパティを追加
}

export function Model(props: ModelProps) {
  const { colors } = props;
  const { nodes, materials } = useGLTF("/model/tea_1.glb") as GLTFResult;
  if (colors && colors.length >= 2) {
    console.log("a");
    console.log(colors);
    materials["Material.009"].color = new THREE.Color(colors[0]);
    materials["Material.002"].color = new THREE.Color(colors[1]);
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.003"]}
        position={[-0.303, 0.58, 0.621]}
        rotation={[-2.542, -0.03, -0.817]}
        scale={[-0.145, -0.285, -0.251]}
      />
      <group
        position={[-1.072, -0.847, -0.008]}
        rotation={[0, 0, 0.226]}
        scale={[0.171, 0.24, 0.189]}
      >
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.cup} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.茶} />
      </group>
      {/* リボン始まり */}
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.009"]}
        position={[-0.446, -0.395, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.031}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.009"]}
        position={[-0.446, -0.395, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.044, 0.031, 0.034]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.009"]}
        position={[-0.446, -0.395, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.028}
      />
      {/* リボン終わり */}
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Fur}
        position={[-0.092, 0.137, -0.001]}
        scale={[0.651, 0.721, 0.646]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.eye}
        position={[-0.554, 0.298, 0.15]}
        scale={0.075}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.Fur}
        position={[0.197, -0.59, -0.001]}
        rotation={[0, 0, -0.031]}
        scale={[0.595, 0.386, 0.503]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Fur}
        position={[-0.157, -0.485, 0.35]}
        rotation={[0, 0, -0.367]}
        scale={[0.189, 0.455, 0.15]}
      />
      {/* 首輪 */}
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials["Material.002"]}
        position={[0.021, -0.378, 0]}
        rotation={[0, 0, 0.285]}
        scale={0.368}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-0.592, 0.061, -0.01]}
        rotation={[-0.088, 0.012, -0.012]}
        scale={[0.155, 0.21, 0.299]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.eye}
        position={[-0.672, 0.161, -0.01]}
        scale={[-0.056, -0.056, -0.058]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.eye}
        position={[-0.692, 0.153, -0.01]}
        scale={[-0.037, -0.037, -0.015]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere016.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere017.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere018.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere019.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere021.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere025.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere027.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere028.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere029.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere030.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere032.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere033.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere034.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere035.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere036.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere037.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere038.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere039.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere040.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere041.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere042.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere043.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere044.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere045.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere046.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere049.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere050.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere051.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere052.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere053.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere054.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere056.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere057.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere058.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere059.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere060.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere061.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere062.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere063.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere064.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere065.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere066.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere067.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere068.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere069.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere070.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere071.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere072.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere073.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere074.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere075.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere076.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere077.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere078.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere079.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere080.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere081.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere082.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere083.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere084.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere086.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere087.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere088.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere089.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere090.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere091.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere092.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere093.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere094.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere095.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere096.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere097.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere098.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere099.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere100.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere101.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere102.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere103.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere104.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere105.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere106.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere107.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere108.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere109.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere112.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere114.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere116.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere117.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere118.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere119.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere121.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere122.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere123.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere125.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere126.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere127.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere128.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere129.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere130.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere131.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere133.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere134.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere135.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere138.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere139.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere140.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere141.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere142.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere143.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere144.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere145.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere146.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere147.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere148.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere149.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere150.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere151.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere152.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere153.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere154.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere155.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere156.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere157.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere158.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere159.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere160.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere162.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere163.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere164.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere165.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere166.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere167.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere168.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere169.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere170.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere172.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere173.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere174.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere175.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere176.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere177.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere178.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere179.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere180.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere181.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere182.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere183.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere184.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere185.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere187.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere189.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere191.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere192.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere194.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere195.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere197.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere198.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere199.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere200.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere201.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere202.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere203.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere204.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere205.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere206.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere207.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere208.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere209.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere210.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere211.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere212.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere213.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere214.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere215.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere216.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere217.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere218.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere219.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere220.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere221.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere222.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere223.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere224.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere225.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere226.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere227.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere228.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere229.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere230.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere231.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere232.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere233.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere234.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere235.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere236.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere237.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere238.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere239.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.Sphere240.geometry}
        material={materials.Furskin}
        position={[-0.092, 0.658, 0.651]}
        rotation={[-0.53, 0, 0]}
        scale={0.995}
      />
    </group>
  );
}

useGLTF.preload("/tea_1.glb");
